#!/usr/bin/env node
/**
 * Interactive first-time setup.
 *
 * Asks for the two Supabase values, validates them against the live project,
 * checks whether the database schema has been applied, writes `.env`, and
 * builds the extension. Designed so a non-technical teammate can run it.
 *
 * Usage:  npm run setup
 */
import { createInterface } from 'node:readline/promises';
import { stdin, stdout } from 'node:process';
import { writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env');

const c = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  indigo: (s) => `\x1b[38;5;99m${s}\x1b[0m`,
};

const rl = createInterface({ input: stdin, output: stdout });

async function main() {
  console.log(`
${c.indigo(c.bold('  TeamHue setup'))}
${c.dim('  ─────────────────────────────────────────────')}

  You'll need two values from your Supabase dashboard:
  ${c.dim('Project Settings → API')}

    • Project URL      ${c.dim('https://xxxxx.supabase.co')}
    • anon public key  ${c.dim('a long token starting with eyJ…')}
`);

  if (existsSync(envPath)) {
    const current = await readFile(envPath, 'utf8');
    const url = current.match(/^SUPABASE_URL=(.*)$/m)?.[1]?.trim();
    console.log(c.yellow(`  A .env already exists${url ? ` (${url})` : ''}.`));
    const overwrite = await rl.question('  Replace it? (y/N) ');
    if (!/^y/i.test(overwrite)) {
      console.log(c.dim('\n  Keeping existing .env. Run `npm run build` to rebuild.\n'));
      rl.close();
      return;
    }
    console.log();
  }

  // ---- collect + validate URL
  let url = '';
  while (!url) {
    const raw = (await rl.question('  Project URL: ')).trim().replace(/\/+$/, '');
    if (/^https:\/\/[a-z0-9-]+\.supabase\.(co|in)$/i.test(raw)) {
      url = raw;
    } else {
      console.log(c.red('  ✗ Expected something like https://abcdefgh.supabase.co\n'));
    }
  }

  // ---- collect + validate key
  let key = '';
  while (!key) {
    const raw = (await rl.question('  anon public key: ')).trim();
    if (raw.length < 30) {
      console.log(c.red('  ✗ That looks too short.\n'));
    } else if (/service_role/.test(safeJwtRole(raw))) {
      console.log(
        c.red('  ✗ That is the SERVICE ROLE key — it must never ship in an extension.'),
      );
      console.log(c.red('    Use the "anon public" key instead.\n'));
    } else {
      key = raw;
    }
  }

  // ---- live connectivity + schema check
  console.log(c.dim('\n  Checking connection…'));
  const check = await verify(url, key);

  if (!check.reachable) {
    console.log(c.red(`  ✗ Could not reach the project. ${check.detail}`));
    console.log(c.dim('    Double-check the URL and that the project is running.\n'));
    rl.close();
    process.exit(1);
  }
  console.log(c.green('  ✓ Connected to Supabase'));

  if (!check.schema) {
    console.log(c.yellow('\n  ⚠ The database schema has not been applied yet.'));
    console.log(c.dim('    Open your Supabase dashboard → SQL Editor → New query,'));
    console.log(c.dim('    paste the contents of supabase/schema.sql, and run it.'));
    console.log(c.dim('    Then re-run `npm run setup` (or just `npm run build`).\n'));
  } else {
    console.log(c.green('  ✓ Database schema detected'));
  }

  await writeFile(
    envPath,
    `# TeamHue configuration — generated by \`npm run setup\`\n` +
      `# The anon key is public by design and gated by Row Level Security.\n` +
      `# Never put the service_role key in this file.\n\n` +
      `SUPABASE_URL=${url}\nSUPABASE_ANON_KEY=${key}\n`,
    'utf8',
  );
  console.log(c.green('  ✓ Wrote .env'));

  console.log(c.dim('\n  Building the extension…\n'));
  rl.close();
  execFileSync('node', [resolve(root, 'scripts/build.mjs')], { stdio: 'inherit' });

  console.log(`${c.green(c.bold('  You\u2019re ready.'))}

  ${c.bold('1.')} Open ${c.indigo('chrome://extensions')}
  ${c.bold('2.')} Turn on ${c.bold('Developer mode')} (top-right)
  ${c.bold('3.')} Click ${c.bold('Load unpacked')} and choose ${c.indigo(resolve(root, 'dist'))}
  ${c.bold('4.')} Create your team, then share the join code with teammates
${check.schema ? '' : c.yellow('\n  Remember to run supabase/schema.sql first.\n')}`);
}

/** Decodes a JWT payload just far enough to read its `role` claim. */
function safeJwtRole(token) {
  try {
    const payload = token.split('.')[1];
    return JSON.parse(Buffer.from(payload, 'base64').toString('utf8')).role ?? '';
  } catch {
    return '';
  }
}

/** Confirms the project is reachable and whether our tables exist. */
async function verify(url, key) {
  try {
    const res = await fetch(`${url}/rest/v1/workspaces?select=id&limit=1`, {
      headers: { apikey: key, Authorization: `Bearer ${key}` },
    });

    // 200 = table exists and is readable. 401/403 = RLS is on (expected, schema present).
    if (res.ok || res.status === 401 || res.status === 403) {
      return { reachable: true, schema: true, detail: '' };
    }

    // 404 with this error code means the table is missing → schema not applied.
    if (res.status === 404) {
      const root = await fetch(`${url}/rest/v1/`, { headers: { apikey: key } });
      return { reachable: root.ok, schema: false, detail: '' };
    }

    const body = await res.text();
    if (/Invalid API key/i.test(body)) {
      return { reachable: false, schema: false, detail: 'Invalid API key.' };
    }
    return { reachable: true, schema: false, detail: '' };
  } catch (err) {
    return { reachable: false, schema: false, detail: err.message };
  }
}

main().catch((err) => {
  console.error(c.red('\n  ✗ Setup failed:\n'), err);
  rl.close();
  process.exit(1);
});
